/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/z/kernel-work/tools"
#define EXEC_PREFIX "/home/z/kernel-work/tools"
#define BINDIR "/home/z/kernel-work/tools/bin"
#define SBINDIR "/home/z/kernel-work/tools/sbin"
#define LIBEXECDIR "/home/z/kernel-work/tools/libexec"
#define DATAROOTDIR "/home/z/kernel-work/tools/share"
#define DATADIR "/home/z/kernel-work/tools/share"
#define SYSCONFDIR "/home/z/kernel-work/tools/etc"
#define SHAREDSTATEDIR "/home/z/kernel-work/tools/com"
#define LOCALSTATEDIR "/home/z/kernel-work/tools/var"
#define RUNSTATEDIR "/home/z/kernel-work/tools/var/run"
#define INCLUDEDIR "/home/z/kernel-work/tools/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/z/kernel-work/tools/share/doc/bison"
#define INFODIR "/home/z/kernel-work/tools/share/info"
#define HTMLDIR "/home/z/kernel-work/tools/share/doc/bison"
#define DVIDIR "/home/z/kernel-work/tools/share/doc/bison"
#define PDFDIR "/home/z/kernel-work/tools/share/doc/bison"
#define PSDIR "/home/z/kernel-work/tools/share/doc/bison"
#define LIBDIR "/home/z/kernel-work/tools/lib"
#define LISPDIR "/home/z/kernel-work/tools/share/emacs/site-lisp"
#define LOCALEDIR "/home/z/kernel-work/tools/share/locale"
#define MANDIR "/home/z/kernel-work/tools/share/man"
#define PKGDATADIR "/home/z/kernel-work/tools/share/bison"
#define PKGINCLUDEDIR "/home/z/kernel-work/tools/include/bison"
#define PKGLIBDIR "/home/z/kernel-work/tools/lib/bison"
#define PKGLIBEXECDIR "/home/z/kernel-work/tools/libexec/bison"
